#!/usr/bin/env bash

TEST_IMAGE_NAME="${1:?'Missing required parameter: TEST_IMAGE_NAME'}"

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/utils"

print_colorized WARN "Cleanup Anchore CLI: Deleting virtualenv, cache, build and testing temp data"; echo

continue_prompt

rm -rf "${VENV}" \
    ./*.egg-info \
    dist \
    build \
    .tox

find . \( -type f -name "*.py[co]" -o -type d -name "__pycache__" \) -delete

print_colorized WARN "Deleting Docker image '${TEST_IMAGE_NAME}'"

continue_prompt

docker rmi "${TEST_IMAGE_NAME}"

print_colorized INFO "Finished cleanup of Anchore CLI"; echo
