#!/usr/bin/env bash

# This is in its own script so it can be called from make

o_system=$(uname -s)
if [[ ${o_system} == "Linux" ]]; then
  echo $(getent group docker | cut -d: -f3)
#elif [[ ]]; then
  # TODO how do I do this on MacOS? dscl?
#  echo $(getent group docker | cut -d: -f3)
else
  echo "Unknown GID"
fi
