#!/usr/bin/env bash

PYTHON="${1:?'required parameter: PYTHON'}"

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/utils"

setup_colors

# Declare default tox envs, but allow TOX_ENV to override 
default_tox_envs="py36-anchore_latest py36-anchore_0.6.0 py36-anchore_0.5.1"
tox_env="${TOX_ENV:-$default_tox_envs}"

hash tox || "${PYTHON}" -m pip install -q tox

print_colorized INFO "Running Anchore CLI functional tests..."; echo

for e in $(echo "${tox_env}"); do
    print_colorized INFO "Running functional tests using tox env $e..."
    tox -c test/functional/tox.ini -e "$e" --result-json .tox/functional-test-report.log
    print_colorized INFO "Finished running functional tests using tox env $e."
done

print_colorized INFO "Finished running Anchore CLI functional tests."; echo
