#!/usr/bin/env bash

COMMIT_SHA="${1:?'required parameter'}"
DEV_IMAGE_REPO="${2:?'required parameter'}"
GIT_TAG="${3:?'required parameter'}"

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/utils"

print_colorized WARN "Rebuilding Anchore CLI image '${TEST_IMAGE_NAME}'."; echo

dev_image="${DEV_IMAGE_REPO}:${COMMIT_SHA}"
rebuild_image="${PROD_IMAGE_REPO}:${GIT_TAG}"

if [[ "${CI:-false}" == true ]]; then
    # Test for required environment variables exported in CI jobs
    test "${DOCKER_USER:?'Missing required env variable: DOCKER_USER'}"
    test "${DOCKER_PASS:?'Missing required env variable: DOCKER_PASS'}"
    test "${PROD_IMAGE_REPO:?'Missing required env variable: PROD_IMAGE_REPO'}"

    echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin

    print_colorized WARN "Pulling dev image for release candidate ${dev_image}."; echo
    docker pull "${dev_image}"

    print_colorized WARN "Tagging and pushing image ${rebuild_image}."; echo
    docker tag "${dev_image}" "${rebuild_image}"
    docker push "${rebuild_image}"
else
    print_colorized ERROR "Anchore CLI production images can only be pushed in the CI environment."; echo
fi
