#!/usr/bin/env bash

PYTHON="${1:?'required parameter'}"

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/utils"

setup_colors

# Declare default tox envs, but allow TOX_ENV to override
default_tox_envs="py27 py36"
tox_env="${TOX_ENV:-$default_tox_envs}"

hash tox || "${PYTHON}" -m pip install -q tox

print_colorized INFO "Running Anchore CLI unit tests..."; echo

for e in $(echo "${tox_env}"); do
    print_colorized INFO "Running unit tests using tox env $e..."
    tox -e "$e" --result-json .tox/unit-test-report.log
    print_colorized INFO "Finished running unit tests using tox env $e."
done

print_colorized INFO "Finished running Anchore CLI unit tests."; echo
