#!/usr/bin/env bash

# Utility functions, helpful for the CI process

# A simple y/n prompt
continue_prompt() {
    while true; do
        read -rp "Do you want to continue? " yn
        case ${yn} in
            [Yy]* ) break;;
            [Nn]* ) exit;;
            * ) echo "Please answer yes or no. ";;
        esac
    done
}

# Prints a message using the specified color code, resetting afterwards
# One of OK, WARN, INFO, ERROR
print_colorized() {
    local color_code="${1:?'Missing required parameter: color_code'}"
    local message="${2:?'Missing required parameter: message'}"

    printf "\n${!color_code}%s${NORMAL}\n" "${message}"
}

# Setup shell colors for print statements
# OK:     green
# WARN:   yellow
# INFO:   cyan
# ERROR:  red
# RESET:  reset colors
setup_colors() {
    export OK="\033[0;32m" \
        WARN="\033[0;33m" \
        INFO="\033[0;36m" \
        ERROR="\033[0;31m" \
        RESET="\033[0m"
}

setup_colors
