#!/usr/bin/env bash

# source utility functions
# shellcheck source=SCRIPTDIR/utils
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/utils"

##########################################################
###   PROJECT SPECIFIC TASK COMMANDS - RUNTIME ORDER   ###
########################################################

# These functions are intended to be utilized as task commands invoked from the run_make_task script

build() {
    local COMMIT_SHA="${1:?'required parameter'}"
    local TEST_IMAGE_NAME="${2:?'required parameter'}"

    print_colorized WARN "building image ${TEST_IMAGE_NAME}"
    docker build --target anchore-cli-builder -t anchore-cli:builder -f ./Dockerfile .
    docker build --build-arg CLI_COMMIT="${COMMIT_SHA}" -t "${TEST_IMAGE_NAME}" -f ./Dockerfile .
    print_colorized WARN "successfully built image -- ${TEST_IMAGE_NAME}"
}

lint() {
    local PYTHON="${1:?'required parameter'}"
    local VENV="${2:?'required parameter'}"

    activate_venv "${VENV}"
    hash tox || "${PYTHON}" -m pip install -q tox

    print_colorized WARN "linting project"
    tox -e flake8
}

unit_tests() {
    local PYTHON="${1:?'required parameter'}"
    local VENV="${2:?'required parameter'}"

    # Declare default tox environments, but allow TOX_ENV environment variable to override if it's set
    local default_tox_envs="py27 py36"
    local tox_env="${TOX_ENV:-$default_tox_envs}"

    activate_venv "${VENV}"
    hash tox || "${PYTHON}" -m pip install -q tox

    for e in $(echo "${tox_env}"); do
        print_colorized WARN "running unit tests using tox env - $e"
        tox -e "$e" --result-json .tox/test-reports.log
    done
}

functional_tests() {
    local PYTHON="${1:?'required parameter'}"
    local VENV="${2:?'required parameter'}"

    # Declare default tox environments, but allow TOX_ENV environment variable to override if it's set
    local default_tox_envs="py36-anchore_latest py36-anchore_0.6.0 py36-anchore_0.5.1"
    local tox_env="${TOX_ENV:-$default_tox_envs}"

    activate_venv "${VENV}"
    hash tox || "${PYTHON}" -m pip install tox

    for e in $(echo "${tox_env}"); do
        print_colorized WARN "running functional tests using tox env - $e"
        tox -c tests/functional/tox.ini -e "$e" --result-json .tox/test-reports.log
    done
}

setup_e2e_tests() {
    local COMMIT_SHA="${1:?'required parameter'}"
    local DEV_IMAGE_REPO="${2:?'required parameter'}"
    local GIT_TAG="${3:?'required parameter'}"
    local TEST_IMAGE_NAME="${4:?'required parameter'}"
    local VENV="${5:?'required parameter'}"

    local cli_image
    activate_venv "${VENV}"

    if [[ "${GIT_TAG}" =~ ^v[0-9]+(\.[0-9]+)*$ ]]; then
        # get the latest rc git tag for this semver & use it for the image tag
        cli_image="${DEV_IMAGE_REPO}:$(git describe --match "${GIT_TAG}-rc*" --tags --abbrev=0)"
        print_colorized WARN "detected semver git tag, using RC image for e2e testing -- ${cli_image}"

    elif docker inspect "${TEST_IMAGE_NAME}" &> /dev/null; then
        cli_image="${TEST_IMAGE_NAME}"
        print_colorized WARN "using local dev image for e2e testing -- ${cli_image}"
        kind load docker-image "${cli_image}" --name e2e-testing

    else
        cli_image="${DEV_IMAGE_REPO}:${COMMIT_SHA}"
        print_colorized WARN "using remote dev image for e2e testing -- ${cli_image}"
    fi

    if [[ "${CI:-false}" == true ]]; then
        # Test for required environment variables exported in CI jobs
        test "${DOCKER_PASS:?'required environment variable'}"
        test "${DOCKER_USER:?'required environment variable'}"

        # create k8s secret using $DOCKER_USER & $DOCKER_PASS and set as default imagePullCreds
        kubectl create secret docker-registry anchore-enterprise-pullcreds --docker-server=docker.io --docker-username="${DOCKER_USER}" --docker-password="${DOCKER_PASS}" --docker-email=anchoreci@anchore.com
        kubectl patch serviceaccount default --type=merge --patch '{"imagePullSecrets":[{"name": "anchore-enterprise-pullcreds"}]}'
    fi

    if ! helm list | grep e2e-testing; then
        helm repo add stable https://kubernetes-charts.storage.googleapis.com
        helm install e2e-testing -f tests/e2e/base-values.yaml --set anchoreGlobal.image=anchore/anchore-engine-dev:latest stable/anchore-engine | head -n6
    fi

    if ! kubectl get pods | grep anchore-cli; then
        kubectl run anchore-cli --image=${cli_image} --restart=Never --command -- tail -f /dev/null
        while [[ $(kubectl get pods anchore-cli -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]] &> /dev/null; do echo "waiting for anchore-cli pod" && sleep 3; done
    fi
}

run_e2e_tests() {
    local PYTHON="${1:?'required parameter'}"
    local VENV="${2:?'required parameter'}"

    local exec_anchorecli="kubectl exec anchore-cli -- anchore-cli --u admin --p foobar --url http://e2e-testing-anchore-engine-api:8228/v1/"
    activate_venv "${VENV}"

    print_colorized WARN "running e2e tests"
    eval "${exec_anchorecli} --version"
    eval "${exec_anchorecli} system wait --timeout 300 --interval 10 --feedsready '' --servicesready 'catalog,apiext,policy_engine,simplequeue,analyzer'"
    eval "${exec_anchorecli} system status"
    "${PYTHON}" tests/e2e/aetest.py docker.io/alpine:latest "${exec_anchorecli}"
    "${PYTHON}" tests/e2e/aefailtest.py docker.io/alpine:latest "${exec_anchorecli}"
}

push_dev_image() {
    local COMMIT_SHA="${1:?'required parameter'}"
    local DEV_IMAGE_REPO="${2:?'required parameter'}"
    local GIT_BRANCH="${3:?'required parameter'}"
    local TEST_IMAGE_NAME="${4:?'required parameter'}"

    local dev_image
    local latest_image
    local branch_image

    dev_image="${DEV_IMAGE_REPO}:${COMMIT_SHA}"
    latest_image="${DEV_IMAGE_REPO}:latest"
    branch_image="${DEV_IMAGE_REPO}:${GIT_BRANCH}"

    if [[ "${CI:-false}" == true ]]; then
        # Test for required environment variables exported in CI jobs
        test "${DOCKER_PASS:?'required environment variable'}"
        test "${DOCKER_USER:?'required environment variable'}"
        test "${RELEASE_BRANCHES:?'required environment variable'}"

        echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin

        print_colorized WARN "tagging and pushing image -- ${dev_image}"
        docker tag "${TEST_IMAGE_NAME}" "${dev_image}"
        docker push "${dev_image}"

        if [[ "${GIT_BRANCH}" == 'master' ]]; then
            print_colorized WARN "tagging & pushing image -- ${latest_image}"
            docker tag "${dev_image}" "${latest_image}"
            docker push "${latest_image}"

        elif [[ "${RELEASE_BRANCHES}" == *"${GIT_BRANCH}"* ]]; then
            print_colorized WARN "tagging & pushing image -- ${branch_image}"
            docker tag "${dev_image}" "${branch_image}"
            docker push "${branch_image}"
        fi
    else
        print_colorized WARN "tagging and pushing image -- ${dev_image}"
        continue_prompt
        docker tag "${TEST_IMAGE_NAME}" "${dev_image}"
        docker push "${dev_image}"
    fi
}

push_rc_image() {
    local DEV_IMAGE_REPO="${1:?'required parameter'}"
    local GIT_TAG="${2:?'required parameter'}"
    local TEST_IMAGE_NAME="${3:?'required parameter'}"

    local rc_image
    local rc_latest_image

    rc_image="${DEV_IMAGE_REPO}:${GIT_TAG}"
    rc_latest_image="${DEV_IMAGE_REPO}:rc"

    if [[ "${CI:-false}" == true ]]; then
        # Test for required environment variables exported in CI jobs
        test "${DOCKER_PASS:?'required environment variable'}"
        test "${DOCKER_USER:?'required environment variable'}"

        echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin

        print_colorized WARN "tagging and pushing image -- ${rc_image}"
        docker tag "${TEST_IMAGE_NAME}" "${rc_image}"
        docker push "${rc_image}"

        print_colorized WARN "tagging and pushing image -- ${rc_latest_image}"
        docker tag "${rc_image}" "${rc_latest_image}"
        docker push "${rc_latest_image}"
    else
        print_colorized WARN "CI=true must be set to push image -- ${rc_image}"
    fi
}

push_prod_image_release() {
    local DEV_IMAGE_REPO="${1:?'required parameter'}"
    local GIT_BRANCH="${2:-'required parameter'}"
    local GIT_TAG="${3:?'required parameter'}"

    local latest_image
    local prod_image
    local rc_image

    latest_image="${PROD_IMAGE_REPO}:latest"
    prod_image="${PROD_IMAGE_REPO}:${GIT_TAG}"
    rc_image="${DEV_IMAGE_REPO}:$(git describe --match "${GIT_TAG}-rc*" --tags --abbrev=0)"

    if [[ "${CI:-false}" == true ]]; then
        # Test for required environment variables exported in CI jobs
        test "${DOCKER_PASS:?'required environment variable'}"
        test "${DOCKER_USER:?'required environment variable'}"
        test "${LATEST_RELEASE_BRANCH:?'required environment variable'}"
        test "${PROD_IMAGE_REPO:?'required environment variable'}"

        echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin

        print_colorized WARN "pulling RC image for release -- ${rc_image}"
        docker pull "${rc_image}"

        print_colorized WARN "tagging and pushing image -- ${prod_image}"
        docker tag "${rc_image}" "${prod_image}"
        docker push "${prod_image}"

        if [[ "${GIT_BRANCH}" == "${LATEST_RELEASE_BRANCH}" ]] || [[ "${GIT_BRANCH}" == "master" ]]; then
            print_colorized WARN "tagging and pushing image -- ${latest_image}"
            docker tag "${prod_image}" "${latest_image}"
            docker push "${latest_image}"
        fi
    else
        print_colorized ERROR "CI=true must be set to push image -- ${prod_image}"
    fi
}

push_prod_image_rebuild() {
    local COMMIT_SHA="${1:?'required parameter'}"
    local DEV_IMAGE_REPO="${2:?'required parameter'}"
    local GIT_TAG="${3:?'required parameter'}"

    local dev_image
    local rebuild_image

    dev_image="${DEV_IMAGE_REPO}:${COMMIT_SHA}"
    rebuild_image="${PROD_IMAGE_REPO}:${GIT_TAG}"

    if [[ "${CI:-false}" == true ]]; then
        # Test for required environment variables exported in CI jobs
        test "${DOCKER_PASS:?'required environment variable'}"
        test "${DOCKER_USER:?'required environment variable'}"
        test "${PROD_IMAGE_REPO:?'required environment variable'}"

        echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin

        print_colorized WARN "pulling dev image for release candidate -- ${dev_image}"
        docker pull "${dev_image}"

        print_colorized WARN "tagging and pushing image -- ${rebuild_image}"
        docker tag "${dev_image}" "${rebuild_image}"
        docker push "${rebuild_image}"
    else
        print_colorized ERROR "CI=true must be set to push image -- ${rebuild_image}"
    fi
}